name: flutter_staggered_grid_view
description: A Flutter staggered grid view
version: 0.3.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_staggered_grid_view
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"